name: Matrix
on: push

jobs:
  node-version:
    strategy:
      matrix:
        os: [ubuntu-16.04, ubuntu-20.04]
        node_version: [6, 8, 10]
      max-parallel: 2

    runs-on: ${{ matrix.os }}

    steps:
      - name: Log node version on ${{ matrix.os }}
        run: node -v

      - name: Setup node ${{ matrix. node_version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node_version }}

      - name: Log node version ( ${{ matrix.node_version }}) on ${{ matrix.os }}
        run: node -v
